Increment 23
fishus/go-advanced-metrics pull request #26
Opened 2024-05-01 20:05 UTC by fishus

Обновлён graceful shutdown

2024-05-03 15:25 UTC, tmvrus requested changes
- очень вольное обращение с ошибками
- крайне странная работа с флагами

2024-05-03 15:25 UTC, tmvrus commented on cmd/server/flags.go
> +	}
для этого есть библиотека flag

2024-05-03 15:25 UTC, tmvrus commented on cmd/server/flags.go
> +		log.Println(err)
а как клиент поймет что конфигураций пользоваться нельзя потому что была ошибка?

2024-05-03 15:25 UTC, tmvrus commented on cmd/server/flags.go
> +		return config
а как клиент поймет что конфигураций пользоваться нельзя потому что была ошибка?

2024-05-03 15:25 UTC, tmvrus commented on cmd/server/flags.go
> +	_ = flag.String("c", "", configUsage+" (shorthand)")
???

2024-05-03 16:25 UTC, fishus commented on cmd/server/flags.go
> +	}
> для этого есть библиотека flag

@tmvrus У меня была идея: если указан флаг -c/config и прочитали конфиг, то эти значения становятся значениями по-умолчанию при чтении других флагов и переменных окружения.
Если прочитать все флаги сразу, а flag.Parse можно вызвать только один раз, про придётся писать сравнение значений ручками.
Из двух зол, на мой взгляд, выбрал меньшее.

2024-05-03 16:26 UTC, fishus commented on cmd/server/flags.go
> +		log.Println(err)
> а как клиент поймет что конфигураций пользоваться нельзя потому что была ошибка?

@tmvrus Из лога. Или предлагается выбрасывать panic?

2024-05-03 16:26 UTC, fishus commented on cmd/server/flags.go
> +		return config
> а как клиент поймет что конфигураций пользоваться нельзя потому что была ошибка?

@tmvrus Из лога. Или предлагается выбрасывать panic?

2024-05-03 16:53 UTC, fishus commented on cmd/server/flags.go
> +	_ = flag.String("c", "", configUsage+" (shorthand)")
> ???

@tmvrus кейс: передали одновременно флаг -c/config и другие флаги. Обработка флага -c/config происходит в отдельной функции. В этой функции происходит обработка flag.Parse и я не нашёл другого способа реализовать игнорирование ранее обработанного флага -c/config. В противном случае получу ошибку, что передан флаг, который не обрабатывается (-c/config).

2024-05-05 20:53 UTC, tmvrus approved these changes

2024-05-05 20:53 UTC, tmvrus commented on cmd/server/flags.go
> +	return
можно было обойтись одним return

2024-05-05 20:53 UTC, tmvrus commented on internal/handlers/middleware/decrypt.go
> +			}
эта проверка тут лишена смысла, поскольку уже была выполнена когда добавлялась middleware

2024-05-05 21:57 UTC, merged